### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by IvanSanchez** [Mapwize/mapwize.js-dist#1]
This repo is missing a license - specially troubling for me since the code includes some of _my_ code, with no references to its source or license.

**Comment by mathieugerard** [comment]
Dear Ivan. Indeed, the library is in heavy development and we didn't had the time to finalize the license file yet. We'll take care of that ASAP. However, we definitely acknowledge the work made by the contributors of the open-source projects we are building on, and in particular Leaflet, see credits in www.mapwize.io/map.

**Comment by IvanSanchez** [comment]
> see credits in www.mapwize.io/map

a) I cannot see that page, as it fails because of it not loading google analytics because of adblockers,

b) In https://www.mapwize.io/credits.html I see no references to https://github.com/MazeMap/Leaflet.LayerGroup.Collision

**Comment by mathieugerard** [comment]
You are right. The credits page and the licence file need to be updated to include a reference to your MIT licence. Sorry about that. I will let you know as soon as this is done.

**Comment by mikaelkindborg** [comment]
Hello, have you decided on a license yet?

**Comment by mathieugerard** [comment]
Hi. 
This project has been deprecated a long time ago. We invite you to migrate to our latest JS SDK. You can find the details at docs.mapwize.io.
Regards
Mathieu
