### ISSUE TITLE
Api places.list not working without parameter

### ISSUE THREAD

**Issue by tnargib** [Mapwize/mapwize.js-dist#3]
When I try to load all the available places of my venue with the exemple in the doc I get this error 
`Uncaught TypeError: Cannot read property 'id' of undefined
    at mapwize.js:572`

It seems like it's waiting for a placeList id. Am I missing something ?

My code 
`Mapwize.Api.places.list({}, function (err, places) {
			console.log(places);
		});`

**Comment by tnargib** [comment]
I would loved to provide a JSFiddle to reproduce the issue but I couldn't find a cdn. It could be great to have one later !

**Comment by tnargib** [comment]
Ok I figured out where was the problem. I thought calling the method without parameter would return all available places. But you actually have to provide a venue id.

```
Mapwize.Api.places.list({venueId: <yourVenueId>}, function (err, places) {
	// places contain all places you can access
	console.log(places);
});
```

It would be great to update the documentation as the _**places.list**_ function don't have venueId parameter in it. ^^

**Comment by mathieugerard** [comment]
Happy to see you managed to make it work.
We will update the documentation.
Thanks for the feedback!

2017-10-12 10:40 GMT+02:00 Tnargib <notifications@github.com>:

**Comment by mathieugerard** [comment]
Hi. 
This project has been deprecated a long time ago. We invite you to migrate to our latest JS SDK. You can find the details at docs.mapwize.io.
Regards
Mathieu
