### ISSUE TITLE
Need an Example for apwize.Api.getDirections

### ISSUE THREAD

**Issue by arunmp2004** [Mapwize/mapwize.js-dist#4]
Hi,
Thanks for putting this together. It has been very helpful and easy to try.

Can your provide an example for apwize.Api.getDirections?
Following is what I tried based on the doc, but it the call back error only says, 

Objective, using only the room numbers show the directions on the map.
'Bad Request'

 ```
var from = {
                       "from": {   
                                "placeId": "5af8f53140bc660013814d48",
                                "latitude": "45.06297403306112",
                                "longitude": "-93.15201779420023",
                                "floor": "2",
                                "venueId": "5af713ca9105f90013561596"
                               }
                        };

        var to = {
                    "to": {   
                          "placeId": "5af8f5de0e748c001389c4e1",
                          "latitude": "45.06266910663979",
                          "longitude": "-93.15152435156051",
                          "floor": "2",
                          "venueId": "5af713ca9105f90013561596"
                          }
                        };

        var options = 
                        {
                                "isAccessible": false,
                                "waypointOptimize": false
                        }


        Mapwize.Api.getDirections(from, to, from, options, function(err, directions){
            console.log('Err Recieved >> ' +  err);
                console.log('Directions Recieved >> ' +  directions);
        });
```

**Comment by arunmp2004** [comment]
Found one way out. The Show Direction was working when the waypoint option is removed and it was very handy as mentioned in the doc with only the place id's.


`        map.showDirections({placeId:'5af8f587174d4d0013847714'}, {placeId:'5af8f53140bc660013814d48'}, {isAccessible: 'false', waypointOptimize: 'false'}, function(err, directions){
                        console.log('2222Directions Recieved >> ' + JSON.stringify(directions));
                        console.log('Error Recieved >> ' +  err);
                });`

**Comment by mathieugerard** [comment]
Hi Arun,
Thanks for your feedback.

The form and to objects should directly contain the properties and not "from" or "to" keys.

var from = {
                               "placeId": "5af8f53140bc660013814d48",
                               "latitude": "45.06297403306112",
                               "longitude": "-93.15201779420023",
                               "floor": "2",
                               "venueId": "5af713ca9105f90013561596"
                       };

       var to = {
                         "placeId": "5af8f5de0e748c001389c4e1",
                         "latitude": "45.06266910663979",
                         "longitude": "-93.15152435156051",
                         "floor": "2",
                         "venueId": "5af713ca9105f90013561596"
                       };

Also, the from and to objects can be of different types so not all keys need to be used. If you are using a placeId, you do not need anything else as the place is known on the server side. If you want to use a specific coordinate, then you use latitude, longitude, floor and venueId.

Do not hesitate if you have any further question.
