### ISSUE TITLE
Moving marker feature

### ISSUE THREAD

**Issue by antoineb19** [Mapwize/mapwize.js-dist#5]
The current API allows to create and remove markers. Would it be possible to enable the functionality to move markers ? It would be some kind of `map.moveMarker(markerId, latitude, longitude, floor)` function.  
With my understanding of the underlying code it looks not so difficult to add this functionnality, but I cannot directly modify the `mapwize.js` minified file provided in the repository.

**Comment by mathieugerard** [comment]
Hi Antoine. Indeed, it would be interesting to be able to move markers and it's indeed not too complicated to add.
We'll have a look and try add this.

**Comment by mathieugerard** [comment]
Hi. 
This project has been deprecated a long time ago. We invite you to migrate to our latest JS SDK. You can find the details at docs.mapwize.io.
Regards
Mathieu
